
@start_url = http://localhost:3052


###
GET {{start_url}}/

###
GET {{start_url}}/toto

###
// Création d'un utilisateur
POST {{start_url}}/api/users/local/register
Content-Type: application/json

{
  "pseudonym": "Thomas",
  "email": "thomaslaforge@gmail.com",
  "password": "tomtom1234"
}